vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        profile:
            uri_prefix: /assets/uploads/images
            upload_destination: '%kernel.project_dir%/public/assets/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
